        let selectedchildbirthTime = '';
        let childbirthTimes = {}; // 必要であれば時間帯に対応させる
        let selectedChildGender = '';
        let selectedBrothersGender = '';
        let selectedFreshFlowerOption = '';
        let selectedHairMakeupOption = '';
        let visitCount = '';
        let selectedMenu = '';
        let highschoolCount = '';
        let childbirthCount = '';
        let childsgenderCount = '';
        let BrothersgenderCount = '';
        let FreshflowerphotographyCount = '';
        let adulthairmakeupCount = '';
        let selectedSymptom = [];  // 配列として定義
        let selectedFullDate = '';
        let currentDate = new Date();
        let availabilityCache = {};
        let irradiationsCount = ''; <!-- 選択された症状を格納する変数 -->
        let totalAmount = 0; // 合計金額を格納する変数
        let menuPrice = 0; // メニューの価格
        let optionsPrice = 0; // オプションの合計価格
